version: "3.8"

networks: 
  vote: 
    driver: bridge

volumes: 
   db-data: 

services: 
    vote: 
      image: iv41879/vote:latest
      build:
        context: ./vote
        dockerfile: Dockerfile
      ports: 
        - 80
      networks: 
        - vote
      depends_on: 
        - redis

    redis: 
      image: arm64v8/redis:6.0-alpine
      networks: 
        - vote
    
    worker: 
      image: iv41879/worker:latest
      build:
        context: ./worker
        dockerfile: Dockerfile
      networks: 
        - vote
      depends_on: 
        - redis
        - db
 
    db: 
      image: postgres:9.4
      networks: 
        - vote
      volumes:
        - "db-data:/var/lib/postgresql/data"
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
   
    result: 
      image: iv41879/result:latest
      build: 
        context: ./result
        dockerfile: Dockerfile
      ports:
        - 80
      depends_on: 
        - db
      networks: 
        - vote
    
